{% set version = "1.4.3" %}

package:
  name: genv
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/genv/genv-{{ version }}.tar.gz
  sha256: 8a336884b1aea3b62d17d0f0d39a9f46b91e516e301039d79172eb2275b4d494

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - psutil
    - setuptools

test:
  commands:
    - genv version

about:
  home: https://github.com/run-ai/genv
  summary: GPU environment and cluster management
  description: |
    Genv lets you easily control, configure, monitor and enforce the GPU resources that you are using.
    It is intendend to improve the life of individual GPU users as well as teams that share multi-GPU machines.
    This project was highly inspired by pyenv and other version, package and environment management software like Conda, nvm, rbenv.
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - razrotenberg
